// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkn66bJTPDZ3xXKtdWx9MPQdC3OjET4U',
    appId: '1:666829845119:web:156610ee9401bd49aec54a',
    messagingSenderId: '666829845119',
    projectId: 'chat-app-63f79',
    authDomain: 'chat-app-63f79.firebaseapp.com',
    storageBucket: 'chat-app-63f79.appspot.com',
    measurementId: 'G-3CCL0D1E5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5xTg3Z_TAPyz9dvbYw6fsqaewvE1c4E',
    appId: '1:666829845119:android:7e672fc63ec6ba02aec54a',
    messagingSenderId: '666829845119',
    projectId: 'chat-app-63f79',
    storageBucket: 'chat-app-63f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjP5-luRqWHPl8CupN74BxqvRJ5k_-Oo',
    appId: '1:666829845119:ios:ff75a08ab986f7b5aec54a',
    messagingSenderId: '666829845119',
    projectId: 'chat-app-63f79',
    storageBucket: 'chat-app-63f79.appspot.com',
    iosBundleId: 'com.sangvaleap.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjP5-luRqWHPl8CupN74BxqvRJ5k_-Oo',
    appId: '1:666829845119:ios:54e161fdf69b8867aec54a',
    messagingSenderId: '666829845119',
    projectId: 'chat-app-63f79',
    storageBucket: 'chat-app-63f79.appspot.com',
    iosBundleId: 'com.sangvaleap.chatApp',
  );
}
